### PR TITLE
Add README section about react-hot-loader problem

### PR DESCRIPTION
**Pull request by kalekseev**
I'm not a best english writer so maybe that can be a starting point for you at least :)

### CODE REVIEW

**Comment by orta** [comment]
I'm not sure I see the problem with this, doesn't the app only provide types which would get ignored?

**Comment by kalekseev** [comment]
@orta related issue https://github.com/relay-tools/relay-compiler-language-typescript/issues/67

**Comment by alloy** [comment]
I’m still not really sure what the actual issue is, though :/ Do you have a good grasp?

**Comment by kalekseev** [comment]
No, I don't. I have two points:
 - RHL can't guarantee that every module will be processed as required and they don't know how to fix that so they even consider deprecating the project https://github.com/gaearon/react-hot-loader/issues/1024
> The problem - hot reloading is not "complete", a few things left unreplaced.
But usually that is about "unchanged" parts, so should be fine for you, and couldn't fight with them from our side yet.

 - for some reason graphql files are affected by that https://github.com/gaearon/react-hot-loader/issues/1032
> unexpected require(./src/__generated__/AppQuery.graphql.js) from disposed module ./src/App.js

I assume in case of js the implication is that RHL produce the warning but browser still can process the files in our case browser receives raw typescript and throw error.

**Comment by alloy** [comment]
Alrighty, I adjusted it a bit to try to make clear that there’s _something_ on their end, we don’t know what nor do we have control. Thanks!

**Pull request merged**
