### PR TITLE
allow to specify any as a custom scalar

### PR DESCRIPTION
**Pull request by itajaja**
fixes https://github.com/relay-tools/relay-compiler-language-typescript/issues/129

should I add tests? I couldn't find tests that actually tested custom scalars at all

### CODE REVIEW

**Comment by itajaja** [comment]
would you like it on a separate test module, or should I add it to an existing one?

**Comment by itajaja** [comment]
added tests

**Comment by alloy** [comment]
Actually, I now notice there’s [another PR](https://github.com/relay-tools/relay-compiler-language-typescript/pull/126) open that brings us closer to upstream already (except still `unknown` instead of `any`), so we should probably continue from there. (Sorry for being so late to the party, I was on vacation for the past few weeks.)

@jquense What say you, re `unknown` vs `any`?

**Comment by itajaja** [comment]
@alloy, thanks for the comments. it all makes sense. imo, unknown is better and more correct than any as a default. but there are cases when you want to use other types that are not GraphQL types. for example, you might want `Dictionary` scalar type, whose correct ts type is `Record<string, string>`. I think what should be improved then is relay-compiler to allow more choices in how defining scalar types. you could special case `any` because other languages, like flow, has a similar concept, but for anything more custom like Dictionary, things would be a little bit more complicated and would require a different mapping presumably for each language you are targeting.

to conclude, until that's possible, `any` is probably a better choice, because there are some things that are simply impossible with `unknown`.
(but also: the description of scalar talks about passing GQL scalar types to customScalars, but this actually works, and the flow compiler would not choke on this either, probably)

**Comment by alloy** [comment]
> there are cases when you want to use other types that are not GraphQL types

Yup, I agree that it would be great to have support for this. (As a matter of fact, the only custom scalar we have cannot be supported as-is by relay-compiler.) However, imo this should be handled upstream and then trickle down to language plugins. There‘s an open issue that you could add your feedback to https://github.com/facebook/relay/issues/2830.

> (but also: the description of scalar talks about passing GQL scalar types to customScalars, but this actually works, and the flow compiler would not choke on this either, probably, so it could be an option to merge this as is, as an escape hatch, if you deem it appropriate)

I was going to say that too indeed, aside from proper support it looks like upstream and https://github.com/relay-tools/relay-compiler-language-typescript/pull/126 will accept anything, even if that’s not truly the intent. I’d be ok with merging that and have upstream parity, which should allow you to map `JSON` to `any`. In that case, should we just stick with `unknown` as the default?

**Comment by alloy** [comment]
Cool, ok then let’s just go with #126 as-is. Thanks, all! 🙌

**Comment by itajaja** [comment]
agree with all. thanks!

**Pull request closed without merging**
