### PR TITLE
Add the auto release process

### PR DESCRIPTION
**Pull request by zephraph**
This PR adds [auto](https://github.com/intuit/auto) to automatically release changes on PRs. I still have work to do around setting env variables in Travis. 

### Todo
- [x] In CI create an .npmrc file w/ a publish token
- [x] Add `GH_TOKEN` to CI

### CODE REVIEW

**Comment by orta** [comment]
I added you as an admin, so you should be able to do the CI stuff

**Comment by zephraph** [comment]
I'll round back up on this tomorrow. I've just got to remember how you set keys in Travis 😄 . It's been a minute.

**Comment by zephraph** [comment]
@orta or @alloy... what github account do you want to be responsible for pushing these changes? I ultimately need an npm & github token. Is there a `relay-tools` bot?

**Comment by alloy** [comment]
There is no such bot. I can create tokens for you on my account for now, I'll reach out to you privately.

**Comment by zephraph** [comment]
@alloy this is ready for your final review/merging

One note: there's a command that checks the PR for a sem-ver label. If a label isn't present, it'll fail the PR. Adding a label doesn't actually rerun the build... so you can either ignore the error after adding the label and merge anyway or manually retrigger the build. Really can't wait for github actions to become public....

**Comment by alloy** [comment]
Awesome, thanks! Looks great, so let’s do this 🚀✨

**Comment by kastermester** [comment]
@zephraph Is it possible to get the version tagged in the repo as well? Bonus points if we can generate a commit that updates the version in package.json and tags that commit :) Great work though :D

**Comment by alloy** [comment]
This must have something to do with it https://travis-ci.org/relay-tools/relay-compiler-language-typescript/builds/577335528#L362

**Pull request merged**
